language: node_js
before_install:
  - npm install -g jspm
  - jspm config registries.github.remote https://github.jspm.io
  - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
  - jspm config registries.github.maxRepoSize 100
  - jspm config registries.github.handler jspm-github
  - jspm install
